"""
Built-in post templates — content prompts and starting points.

Each template is a dict with: id, emoji, title, description, category, color.
Colors are CSS rgb strings used for the card accent.
"""

CATEGORIES = [
    {"slug": "all", "label": "All", "icon": "layout-grid"},
    {"slug": "tip", "label": "Tip", "icon": "lightbulb"},
    {"slug": "case-study", "label": "Case Study", "icon": "scroll-text"},
    {"slug": "story", "label": "Story", "icon": "book-open"},
    {"slug": "how-to", "label": "How-to", "icon": "pickaxe"},
    {"slug": "question", "label": "Question", "icon": "message-circle-question"},
    {"slug": "opinion", "label": "Opinion", "icon": "quote"},
    {"slug": "list", "label": "List", "icon": "clipboard-list"},
    {"slug": "behind-the-scenes", "label": "Behind the Scenes", "icon": "clapperboard"},
]

# Six rotating accent colors (rgb strings)
COLORS = [
    "255, 203, 49",   # yellow
    "218, 255, 53",   # lime
    "99, 117, 255",   # indigo
    "248, 149, 151",  # pink
    "87, 152, 255",   # blue
    "59, 252, 255",   # cyan
]

FEATURED_IDS = [50, 59, 20]

TEMPLATES = [
    {
        "id": 161,
        "emoji": "\U0001f9e9",
        "title": "Break this down step by step",
        "description": "Use this to break a concept into clear, scannable steps.",
        "category": "how-to",
        "color": COLORS[0],
    },
    {
        "id": 160,
        "emoji": "\U0001f4d8",
        "title": "Teach one clear takeaway",
        "description": "Use this to teach a focused insight your audience can apply immediately.",
        "category": "tip",
        "color": COLORS[1],
    },
    {
        "id": 159,
        "emoji": "\U0001f9ea",
        "title": "Show a product or process in action",
        "description": "Use this to demonstrate how something works using a real scenario.",
        "category": "how-to",
        "color": COLORS[2],
    },
    {
        "id": 158,
        "emoji": "\U0001f3af",
        "title": "Clarify your content or product",
        "description": "Use this to clearly state who your product, service, or content is designed for.",
        "category": "tip",
        "color": COLORS[3],
    },
    {
        "id": 157,
        "emoji": "\U0001f4c8",
        "title": "Document your progress",
        "description": "Use this to show momentum without needing a big win or metric.",
        "category": "behind-the-scenes",
        "color": COLORS[4],
    },
    {
        "id": 156,
        "emoji": "\U0001fa9e",
        "title": "Make your audience feel seen",
        "description": "Use this to reflect a common thought or struggle your audience has.",
        "category": "question",
        "color": COLORS[5],
    },
    {
        "id": 155,
        "emoji": "\U0001f9ed",
        "title": "Reset your content focus",
        "description": "Use this to clarify what you want to be known for right now and cut unnecessary content noise.",
        "category": "tip",
        "color": COLORS[0],
    },
    {
        "id": 140,
        "emoji": "\U0001f680",
        "title": "I didn\u2019t think I could do it \u2014 and then I did",
        "description": "Tell the story of trying something you thought was out of reach. What made you take the leap, and what surprised you about the outcome?",
        "category": "story",
        "color": COLORS[3],
    },
    {
        "id": 139,
        "emoji": "\u2753",
        "title": "Tell me your best tip for [common challenge]",
        "description": "Ask your audience to share their go-to strategy, tool, or mindset for something you\u2019re currently working on.",
        "category": "question",
        "color": COLORS[4],
    },
    {
        "id": 138,
        "emoji": "\U0001f342",
        "title": "Monthly goals",
        "description": "Share your creative, business, or personal goals for the month and invite your audience to do the same.",
        "category": "list",
        "color": COLORS[5],
    },
    {
        "id": 137,
        "emoji": "\U0001f383",
        "title": "Scarier than ghosting",
        "description": "Create a fun, relatable list that ties into both seasonal humor and consistency.",
        "category": "list",
        "color": COLORS[0],
    },
    {
        "id": 136,
        "emoji": "\U0001f383",
        "title": "That time I ghosted\u2026",
        "description": "Tell a story about a time you didn\u2019t follow through on something and what you learned from it.",
        "category": "story",
        "color": COLORS[1],
    },
    {
        "id": 135,
        "emoji": "\U0001f383",
        "title": "3 ways to avoid ghosting",
        "description": "Share quick, practical tips to help your audience stay on top of industry-specific things this season.",
        "category": "tip",
        "color": COLORS[2],
    },
    {
        "id": 134,
        "emoji": "\U0001f383",
        "title": "Behind-the-scenes of not ghosting",
        "description": "Show your process for staying consistent with content during a busy October.",
        "category": "behind-the-scenes",
        "color": COLORS[3],
    },
    {
        "id": 133,
        "emoji": "\U0001f383",
        "title": "What\u2019s scarier?",
        "description": "Spark conversation with a seasonal \u201cwould you rather\u201d style question.",
        "category": "question",
        "color": COLORS[4],
    },
    {
        "id": 132,
        "emoji": "\U0001f4ac",
        "title": "My \u201cAsk Me Anything\u201d moment",
        "description": "Invite your audience to ask you questions about your journey, work, or expertise. Frame it around a specific topic.",
        "category": "question",
        "color": COLORS[5],
    },
    {
        "id": 131,
        "emoji": "\u267b\ufe0f",
        "title": "What I\u2019d do if I had to start over today",
        "description": "Imagine rebuilding from scratch \u2014 no shortcuts, no network. Share the 3 steps you\u2019d take first, and ask your audience what they\u2019d do differently.",
        "category": "opinion",
        "color": COLORS[0],
    },
    {
        "id": 130,
        "emoji": "\U0001f3af",
        "title": "How I landed [result] without [expected method]",
        "description": "Break down a recent win (client, brand deal, growth milestone) and the unconventional way you achieved it.",
        "category": "case-study",
        "color": COLORS[1],
    },
    {
        "id": 129,
        "emoji": "\U0001f4ad",
        "title": "My biggest mindset shift this year",
        "description": "Talk about one belief, perspective, or routine that changed how you approach your work or creativity.",
        "category": "story",
        "color": COLORS[2],
    },
    {
        "id": 128,
        "emoji": "\u2728",
        "title": "How I get inspired when nothing\u2019s working",
        "description": "Share your go-to rituals, tools, or habits that help you find creativity again.",
        "category": "tip",
        "color": COLORS[3],
    },
    {
        "id": 109,
        "emoji": "\u2705",
        "title": "My back-to-school checklist",
        "description": "Share the personal, professional or business habits, tools, and goals you\u2019re prioritizing this season.",
        "category": "list",
        "color": COLORS[5],
    },
    {
        "id": 108,
        "emoji": "\U0001f4dd",
        "title": "Report card for the year so far",
        "description": "Borrow the school \u201creport card\u201d metaphor \u2014 grade yourself on progress toward your goals so far this year.",
        "category": "behind-the-scenes",
        "color": COLORS[0],
    },
    {
        "id": 107,
        "emoji": "\u270f\ufe0f",
        "title": "The assignment I\u2019m giving myself",
        "description": "Frame a goal or habit as a \u201chomework assignment\u201d for accountability.",
        "category": "opinion",
        "color": COLORS[1],
    },
    {
        "id": 106,
        "emoji": "\U0001f392",
        "title": "Back-to-school essentials",
        "description": "Share the tools, apps, or habits you consider \u201cessentials\u201d to kick off a productive season.",
        "category": "list",
        "color": COLORS[2],
    },
    {
        "id": 105,
        "emoji": "\U0001f342",
        "title": "New season, new routine",
        "description": "Share how your daily routine is shifting as the season changes, just like students adjusting back to school.",
        "category": "behind-the-scenes",
        "color": COLORS[3],
    },
    {
        "id": 103,
        "emoji": "\U0001f30e",
        "title": "Share the environment that fuels your creativity",
        "description": "Describe a place or setting that helps you think clearly or feel inspired.",
        "category": "behind-the-scenes",
        "color": COLORS[4],
    },
    {
        "id": 102,
        "emoji": "\U0001f5a5\ufe0f",
        "title": "Show your work environment",
        "description": "Share a snapshot of the space that helps you do your best work.",
        "category": "behind-the-scenes",
        "color": COLORS[5],
    },
    {
        "id": 101,
        "emoji": "\U0001f516",
        "title": "Share a quote that stuck with you",
        "description": "Spark reflection by sharing a line that\u2019s shaped your thinking.",
        "category": "opinion",
        "color": COLORS[0],
    },
    {
        "id": 99,
        "emoji": "\U0001f504",
        "title": "Walk through your midday reset ritual",
        "description": "Walk your audience through the small habits or actions that help you reset and refocus halfway through the day.",
        "category": "how-to",
        "color": COLORS[1],
    },
    {
        "id": 98,
        "emoji": "\U0001f319",
        "title": "Share how you wind down at night",
        "description": "Show your audience how you disconnect, reflect, or prep for the next day.",
        "category": "behind-the-scenes",
        "color": COLORS[2],
    },
    {
        "id": 97,
        "emoji": "\u2600\ufe0f",
        "title": "Share how you optimize your morning workflow",
        "description": "Walk your audience through a personal morning routine or work setup that boosts productivity.",
        "category": "how-to",
        "color": COLORS[3],
    },
    {
        "id": 96,
        "emoji": "\u2712\ufe0f",
        "title": "Introduce (or reintroduce) yourself",
        "description": "Tell your audience who you are, what you create content about, and who it\u2019s for.",
        "category": "story",
        "color": COLORS[4],
    },
    {
        "id": 88,
        "emoji": "\U0001f4f0",
        "title": "5 newsletters I never miss",
        "description": "Curate a list of high-value newsletters for your niche \u2014 and share why they\u2019re worth it.",
        "category": "list",
        "color": COLORS[5],
    },
    {
        "id": 87,
        "emoji": "\U0001f501",
        "title": "One habit I swear by \u2014 and one I\u2019m quitting",
        "description": "Share a personal contrast and invite your audience to do the same.",
        "category": "opinion",
        "color": COLORS[0],
    },
    {
        "id": 86,
        "emoji": "\u2696\ufe0f",
        "title": "Which one are you? [Option A] vs [Option B]",
        "description": "Use contrast to create quick decision-based interaction.",
        "category": "question",
        "color": COLORS[1],
    },
    {
        "id": 85,
        "emoji": "\u270d\ufe0f",
        "title": "Fill in the blank: I wish more people knew ___ about [topic]",
        "description": "A low-lift way to prompt thoughtful replies.",
        "category": "question",
        "color": COLORS[2],
    },
    {
        "id": 84,
        "emoji": "\U0001f643",
        "title": "What\u2019s the best advice you\u2019ve ever ignored?",
        "description": "Spark conversation by sharing a personal \u201cI\u2019m glad I didn\u2019t listen\u201d moment.",
        "category": "question",
        "color": COLORS[3],
    },
    {
        "id": 83,
        "emoji": "\U0001f525",
        "title": "What\u2019s your unpopular opinion about [industry/topic]?",
        "description": "Invite bold responses and challenge the status quo.",
        "category": "opinion",
        "color": COLORS[4],
    },
    {
        "id": 82,
        "emoji": "\U0001f634",
        "title": "This feature is slept on",
        "description": "Highlight an underrated feature of your product or offer that consistently delivers results.",
        "category": "tip",
        "color": COLORS[5],
    },
    {
        "id": 81,
        "emoji": "\u23f3",
        "title": "Why now\u2019s the time to try this",
        "description": "Position your offer or product as timely and relevant \u2014 tied to a trend or seasonal need.",
        "category": "tip",
        "color": COLORS[0],
    },
    {
        "id": 80,
        "emoji": "\u2753",
        "title": "The one question that changed my strategy",
        "description": "Sometimes all it takes is one question to shift everything. Share the moment, the question, and how it reshaped your thinking or direction.",
        "category": "story",
        "color": COLORS[1],
    },
    {
        "id": 77,
        "emoji": "\U0001f502",
        "title": "What I wish I knew before starting my business",
        "description": "Looking back, what would you do differently? Share the lessons that would\u2019ve saved you time, money, or stress \u2014 and help someone else skip the guesswork.",
        "category": "tip",
        "color": COLORS[2],
    },
    {
        "id": 76,
        "emoji": "\u23f1\ufe0f",
        "title": "The system that saves me hours every week",
        "description": "Share one repeatable system that made your work faster, smoother, or more scalable. Break it down step-by-step so others can borrow it.",
        "category": "how-to",
        "color": COLORS[3],
    },
    {
        "id": 75,
        "emoji": "\U0001f4b2",
        "title": "How I\u2019d launch my business with just $500",
        "description": "Imagine starting from scratch with a small budget. Share the tools, priorities, and decisions you\u2019d make to get real results without wasting a cent.",
        "category": "how-to",
        "color": COLORS[4],
    },
    {
        "id": 74,
        "emoji": "\U0001f645\U0001f3fe\u200d\u2642\ufe0f",
        "title": "One thing we stopped doing this year \u2014 and why",
        "description": "What did you let go of this year \u2014 a client type, offer, or habit? Share the decision, the risk, and how it opened space for better results.",
        "category": "opinion",
        "color": COLORS[5],
    },
    {
        "id": 72,
        "emoji": "\U0001f635",
        "title": "When everything went wrong in one week",
        "description": "Share the chaos of a tough week \u2014 what broke, how you responded, and what you\u2019d do differently next time. People relate to the messy parts, too.",
        "category": "story",
        "color": COLORS[1],
    },
    {
        "id": 71,
        "emoji": "\U0001f4c4",
        "title": "The offer no one talks about \u2014 but always performs",
        "description": "What\u2019s one service, product, or offer that quietly delivers great results? Shine a light on it \u2014 and explain why it works so well.",
        "category": "case-study",
        "color": COLORS[2],
    },
    {
        "id": 70,
        "emoji": "\U0001f3eb",
        "title": "One thing we\u2019ve learned from our clients",
        "description": "Working with clients often reveals what no strategy guide can. Share one surprising or valuable lesson that\u2019s shifted how you work or deliver.",
        "category": "case-study",
        "color": COLORS[3],
    },
    {
        "id": 69,
        "emoji": "\U0001f4c8",
        "title": "Why we raised our prices",
        "description": "Share the thought process behind a price increase \u2014 what led to it, how you communicated it, and what happened after the change.",
        "category": "case-study",
        "color": COLORS[4],
    },
    {
        "id": 68,
        "emoji": "\U0001f4c5",
        "title": "What happened in our business this month",
        "description": "Reflect on the last 30 days \u2014 what went right, what didn\u2019t, and what you learned.",
        "category": "behind-the-scenes",
        "color": COLORS[5],
    },
    {
        "id": 67,
        "emoji": "\U0001f3c6",
        "title": "One simple shift that made a big difference this month",
        "description": "What small change \u2014 tool, habit, or tweak \u2014 helped you or your team this month? No major overhaul, just one thing that actually worked.",
        "category": "tip",
        "color": COLORS[0],
    },
    {
        "id": 66,
        "emoji": "\U0001f504",
        "title": "The mistake we made again and again",
        "description": "Share the recurring mistake you kept making \u2014 and the shift that finally broke the cycle.",
        "category": "story",
        "color": COLORS[1],
    },
    {
        "id": 61,
        "emoji": "\U0001f62c",
        "title": "The mistake I can\u2019t forget \u2014 and what it taught me",
        "description": "Share a cringeworthy or painful mistake \u2014 and what it taught you. The goal is to normalize learning out loud, not pretending to be perfect.",
        "category": "story",
        "color": COLORS[2],
    },
    {
        "id": 60,
        "emoji": "\U0001f19a",
        "title": "How I handle things now (vs. then)",
        "description": "Show the difference between your past and present self \u2014 especially how you respond to challenges. What changed, and what helped you grow?",
        "category": "story",
        "color": COLORS[3],
    },
    {
        "id": 59,
        "emoji": "\U0001fa9e",
        "title": "When I realized I was faking confidence",
        "description": "Share the moment you recognized a behavior you thought was strength\u2026 was actually fear. What changed after you saw it clearly?",
        "category": "story",
        "color": COLORS[4],
    },
    {
        "id": 58,
        "emoji": "\U0001f526",
        "title": "The moment I realized I was holding myself back",
        "description": "Describe a situation that made you realize you were playing it safe. What triggered the shift \u2014 and how did you choose to grow from there?",
        "category": "story",
        "color": COLORS[5],
    },
    {
        "id": 57,
        "emoji": "\U0001f300",
        "title": "No 5-year plan \u2014 just progress",
        "description": "Share what happened when you stopped chasing a perfect roadmap and started following what actually felt aligned. What opened up when you let go of control?",
        "category": "opinion",
        "color": COLORS[0],
    },
    {
        "id": 56,
        "emoji": "\U0001f4e9",
        "title": "The message I still think about",
        "description": "Was it a DM, an offhand comment, or a line from a mentor? Share the moment someone\u2019s words reshaped how you see your work or life.",
        "category": "story",
        "color": COLORS[1],
    },
    {
        "id": 55,
        "emoji": "\U0001f4b8",
        "title": "The expensive lesson I\u2019m glad I learned",
        "description": "Talk about a hard-earned insight \u2014 financial or emotional \u2014 that cost you something but gave you clarity or growth in return.",
        "category": "story",
        "color": COLORS[2],
    },
    {
        "id": 54,
        "emoji": "\U0001f9d7",
        "title": "One year ago, I would\u2019ve been terrified to do this",
        "description": "Reflect on something you once feared but now embrace. What changed internally or externally that helped you cross that milestone?",
        "category": "story",
        "color": COLORS[3],
    },
    {
        "id": 53,
        "emoji": "\U0001f3af",
        "title": "The quiet shift that changed everything",
        "description": "Share a subtle moment or realization that ended up changing your path in a big way.",
        "category": "story",
        "color": COLORS[4],
    },
    {
        "id": 52,
        "emoji": "\U0001f6ab",
        "title": "When choosing your own path paid off",
        "description": "What\u2019s one popular piece of advice you chose not to follow \u2014 and how did going your own way lead to growth or success? Share the lesson and how it shaped your journey.",
        "category": "opinion",
        "color": COLORS[5],
    },
    {
        "id": 51,
        "emoji": "\U0001f4cc",
        "title": "Here\u2019s a step-by-step that actually works",
        "description": "Break down a simple, repeatable system that helped you reach a goal. Make it easy for others to follow and adapt to their own work or life.",
        "category": "how-to",
        "color": COLORS[0],
    },
    {
        "id": 50,
        "emoji": "\U0001f9e9",
        "title": "How I turned struggle into structure",
        "description": "Describe a time you replaced a frustrating habit or workflow with a clear system \u2014 and the real results that came from it.",
        "category": "how-to",
        "color": COLORS[1],
    },
    {
        "id": 49,
        "emoji": "\u23f1\ufe0f",
        "title": "How I got results in just 3 days",
        "description": "Share a time-bound challenge where you set a goal and hit it fast. Walk through the steps \u2014 and the result you didn\u2019t expect.",
        "category": "case-study",
        "color": COLORS[2],
    },
    {
        "id": 48,
        "emoji": "\U0001f501",
        "title": "The 3-step system I use every time",
        "description": "Have a task or problem you face often? Share the multi-step method you always return to \u2014 and why it works, even under pressure.",
        "category": "how-to",
        "color": COLORS[3],
    },
    {
        "id": 47,
        "emoji": "\U0001f4cb",
        "title": "My step-by-step process that actually works",
        "description": "Break down your personal method for achieving a goal or solving a problem \u2014 step-by-step. Make it easy for others to follow and adapt.",
        "category": "how-to",
        "color": COLORS[4],
    },
    {
        "id": 46,
        "emoji": "\U0001f422",
        "title": "How slowing down made me more productive",
        "description": "Share what happened when you stopped pushing so hard and gave yourself space \u2014 and how that pause helped you move forward faster.",
        "category": "story",
        "color": COLORS[5],
    },
    {
        "id": 45,
        "emoji": "\U0001f6e0\ufe0f",
        "title": "My honest review of a tool I tried",
        "description": "Give a transparent review of a tool, method, or platform you tested \u2014 what worked, what didn\u2019t, and who you\u2019d recommend it to.",
        "category": "case-study",
        "color": COLORS[0],
    },
    {
        "id": 44,
        "emoji": "\U0001f501",
        "title": "A one-week experiment that changed everything",
        "description": "Tried something new for a week? Share what you changed, what you noticed, and whether you\u2019re sticking with it \u2014 or leaving it behind.",
        "category": "case-study",
        "color": COLORS[1],
    },
    {
        "id": 43,
        "emoji": "\U0001f9ef",
        "title": "When good advice didn\u2019t work for me",
        "description": "Talk about a time you followed popular advice and it totally backfired \u2014 and what actually worked better for your situation.",
        "category": "opinion",
        "color": COLORS[2],
    },
    {
        "id": 42,
        "emoji": "\U0001f9ea",
        "title": "I tested it so you don\u2019t have to",
        "description": "Share a mini case study where you tried a tool, strategy, or habit for a specific goal. Be honest about what worked, what didn\u2019t, and what you learned.",
        "category": "case-study",
        "color": COLORS[3],
    },
    {
        "id": 41,
        "emoji": "\U0001f6aa",
        "title": "I wasn\u2019t ready \u2014 I started anyway",
        "description": "Talk about a time you started without having it all figured out. Show how action \u2014 not certainty \u2014 built the momentum you needed.",
        "category": "story",
        "color": COLORS[4],
    },
    {
        "id": 40,
        "emoji": "\U0001f50d",
        "title": "The little thing that actually matters",
        "description": "What\u2019s one detail, habit, or mindset others overlook \u2014 but you\u2019ve found crucial? Challenge the myth that it doesn\u2019t matter, and explain why it does.",
        "category": "opinion",
        "color": COLORS[5],
    },
    {
        "id": 39,
        "emoji": "\u26a0\ufe0f",
        "title": "When \u201cbest practices\u201d didn\u2019t work for me",
        "description": "Push back on cookie-cutter advice in your field. What did you try, how did it fall short, and what did you do instead that actually worked?",
        "category": "opinion",
        "color": COLORS[0],
    },
    {
        "id": 38,
        "emoji": "\U0001f393",
        "title": "You\u2019re allowed to share before you\u2019re an expert",
        "description": "Tackle the myth that you need credentials to show up online. Share why your experience \u2014 even in progress \u2014 is still valuable to others.",
        "category": "opinion",
        "color": COLORS[1],
    },
    {
        "id": 37,
        "emoji": "\U0001f504",
        "title": "Something I\u2019ve changed my mind about",
        "description": "Share a belief, habit, or opinion you no longer hold \u2014 and what shifted your perspective. Invite others to reflect on what\u2019s changed for them too.",
        "category": "opinion",
        "color": COLORS[2],
    },
    {
        "id": 36,
        "emoji": "\U0001f648",
        "title": "The worst advice I ever followed",
        "description": "What\u2019s a piece of advice or tool that totally backfired on you? Tell the story, the outcome, and what you wish you\u2019d done instead.",
        "category": "story",
        "color": COLORS[3],
    },
    {
        "id": 35,
        "emoji": "\U0001f552",
        "title": "Is this actually productive \u2014 or just popular?",
        "description": "Challenge a routine or belief that gets praised in your industry but doesn\u2019t deliver results. Share your experience \u2014 and ask others for theirs.",
        "category": "opinion",
        "color": COLORS[4],
    },
    {
        "id": 34,
        "emoji": "\U0001f4ac",
        "title": "One thing I\u2019d change in my industry",
        "description": "What\u2019s a norm, habit, or mindset in your field that feels outdated or unhelpful? Share your take \u2014 and invite others to weigh in.",
        "category": "opinion",
        "color": COLORS[5],
    },
    {
        "id": 33,
        "emoji": "\u2753",
        "title": "Is this overrated \u2014 or just misunderstood?",
        "description": "Take a closer look at a trend, tool, or best practice. Share your experience and ask your audience: does it actually help, or is it just hype?",
        "category": "question",
        "color": COLORS[0],
    },
    {
        "id": 32,
        "emoji": "\U0001f6e0\ufe0f",
        "title": "What to try when nothing\u2019s working",
        "description": "If you\u2019ve hit a wall with a goal before, suggest a practical shift that worked for you.",
        "category": "tip",
        "color": COLORS[1],
    },
    {
        "id": 31,
        "emoji": "\U0001f9d0",
        "title": "The biggest misconception in my field",
        "description": "What\u2019s something people consistently misunderstand in your industry or niche? Clear it up with a key insight \u2014 and invite others to weigh in.",
        "category": "opinion",
        "color": COLORS[2],
    },
    {
        "id": 30,
        "emoji": "\u267b\ufe0f",
        "title": "What I\u2019d do if I had to start over today",
        "description": "Imagine rebuilding from scratch \u2014 no shortcuts, no network. Share the 3 steps you\u2019d take first, and ask your audience what they\u2019d do differently.",
        "category": "opinion",
        "color": COLORS[3],
    },
    {
        "id": 29,
        "emoji": "\U0001f9ef",
        "title": "You don\u2019t need what you think you need",
        "description": "Challenge the myth that success requires a certain tool, degree, or habit. Share what actually moved the needle for you \u2014 and why that matters.",
        "category": "opinion",
        "color": COLORS[4],
    },
    {
        "id": 28,
        "emoji": "\U0001f525",
        "title": "Why I stopped following \u201cbest practices\u201d",
        "description": "What\u2019s a popular strategy or belief you\u2019ve rejected \u2014 and what do you do instead? Share your reasoning and ask others how they approach it.",
        "category": "opinion",
        "color": COLORS[5],
    },
    {
        "id": 27,
        "emoji": "\U0001f4ca",
        "title": "When the data finally caught up to what you knew",
        "description": "Share new stats or research that validate a pattern you\u2019ve already seen. Make the case for action \u2014 and who should be paying attention now.",
        "category": "case-study",
        "color": COLORS[0],
    },
    {
        "id": 26,
        "emoji": "\U0001f9e0",
        "title": "It\u2019s more than just a new format",
        "description": "When a new tool or platform catches on, it often reflects a deeper shift. Share what you\u2019re noticing \u2014 and how you\u2019re adjusting to meet the moment.",
        "category": "opinion",
        "color": COLORS[1],
    },
    {
        "id": 25,
        "emoji": "\U0001f4c8",
        "title": "A quiet shift that changes everything",
        "description": "What subtle behavior or pattern have you noticed that signals a bigger transformation? Share the trend, what it means, and how you\u2019re adapting.",
        "category": "opinion",
        "color": COLORS[2],
    },
    {
        "id": 24,
        "emoji": "\U0001f5e3\ufe0f",
        "title": "What no one\u2019s saying about this trend",
        "description": "Take a trend that\u2019s everywhere \u2014 and dig deeper. What are people missing, and what\u2019s the real insight hiding under the hype?",
        "category": "opinion",
        "color": COLORS[3],
    },
    {
        "id": 23,
        "emoji": "\U0001f50d",
        "title": "What this trend really means",
        "description": "Share a popular trend and explain what it really signals about how people work, share, or connect \u2014 and how you\u2019re responding to it.",
        "category": "opinion",
        "color": COLORS[4],
    },
    {
        "id": 22,
        "emoji": "\U0001f4c9",
        "title": "How I got stuck in the comparison trap \u2014 and what I did next",
        "description": "Talk about how comparing yourself to others slowed you down or distorted your goals \u2014 and what mindset shift helped you get back on track.",
        "category": "story",
        "color": COLORS[5],
    },
    {
        "id": 21,
        "emoji": "\u23f3",
        "title": "I should\u2019ve started sooner",
        "description": "Talk about a time perfectionism got in the way \u2014 and what finally helped you take action. Someone else might need that same nudge.",
        "category": "story",
        "color": COLORS[0],
    },
    {
        "id": 20,
        "emoji": "\U0001f4b8",
        "title": "I used to price based on fear, not value",
        "description": "Talk about a time you underpriced your work out of fear or comparison \u2014 and how switching to value-based pricing changed your results and confidence.",
        "category": "story",
        "color": COLORS[1],
    },
    {
        "id": 19,
        "emoji": "\U0001f6e0\ufe0f",
        "title": "The quick fix that made things worse",
        "description": "Share a time a shortcut or bandaid solution didn\u2019t work \u2014 and what longer-term habit, mindset, or strategy actually solved the problem.",
        "category": "story",
        "color": COLORS[2],
    },
    {
        "id": 18,
        "emoji": "\U0001f9ef",
        "title": "It didn\u2019t go how I expected \u2014 and what I learned",
        "description": "Describe a strategy or belief that completely backfired. What did you expect, what actually happened, and what would you do differently now?",
        "category": "story",
        "color": COLORS[3],
    },
    {
        "id": 17,
        "emoji": "\U0001f9d8",
        "title": "One small change that shifted everything",
        "description": "Talk about a situation that felt stuck or overwhelming \u2014 and the small but powerful change in behavior or mindset that made it better.",
        "category": "tip",
        "color": COLORS[4],
    },
    {
        "id": 16,
        "emoji": "\U0001f4c6",
        "title": "The system that saved me",
        "description": "Share a system, habit, or routine that helped you feel less scattered and more in control of your time \u2014 and the before/after difference it made.",
        "category": "how-to",
        "color": COLORS[5],
    },
    {
        "id": 15,
        "emoji": "\U0001f4a1",
        "title": "The obvious solution didn\u2019t work \u2014 this did",
        "description": "Share a time when you chased a common or \u201clogical\u201d fix that didn\u2019t work, and what unexpected solution actually made the difference.",
        "category": "story",
        "color": COLORS[0],
    },
    {
        "id": 14,
        "emoji": "\U0001f680",
        "title": "I didn\u2019t think I could do it \u2014 and then I did",
        "description": "Tell the story of trying something you thought was out of reach. What made you take the leap, and what surprised you about the outcome?",
        "category": "story",
        "color": COLORS[1],
    },
    {
        "id": 13,
        "emoji": "\U0001f504",
        "title": "Before, during, after: what finally worked for me",
        "description": "Walk through a clear transformation \u2014 what you were struggling with, what you tried, and what finally changed. Keep it real and relatable.",
        "category": "case-study",
        "color": COLORS[2],
    },
    {
        "id": 12,
        "emoji": "\U0001f3af",
        "title": "I almost didn\u2019t try it \u2014 but I\u2019m so glad I did",
        "description": "Share a moment of hesitation or doubt that turned into a breakthrough. What made you take the risk, and what was the outcome?",
        "category": "story",
        "color": COLORS[3],
    },
    {
        "id": 11,
        "emoji": "\U0001f9ed",
        "title": "I stopped following the rulebook \u2014 and everything changed",
        "description": "Talk about a time you let go of a \u201cbest practice\u201d or common belief that no longer served you \u2014 and what happened when you found your own way.",
        "category": "opinion",
        "color": COLORS[4],
    },
    {
        "id": 10,
        "emoji": "\U0001f5d3\ufe0f",
        "title": "How I structure my workweek",
        "description": "Give a peek into how you organize your week \u2014 meetings, deep work, creative time, or rest. It doesn\u2019t have to be perfect \u2014 just real.",
        "category": "behind-the-scenes",
        "color": COLORS[5],
    },
    {
        "id": 9,
        "emoji": "\U0001f300",
        "title": "This content format works every time",
        "description": "Share a post format, prompt style, or idea type you keep returning to \u2014 the kind that consistently gets replies, shares, or saves.",
        "category": "tip",
        "color": COLORS[0],
    },
    {
        "id": 8,
        "emoji": "\U0001f3a7",
        "title": "My go-to playlist for focus or reset",
        "description": "Share a playlist or tracks that help you stay grounded, focused, or creatively recharged.",
        "category": "list",
        "color": COLORS[1],
    },
    {
        "id": 7,
        "emoji": "\u2709\ufe0f",
        "title": "The cold email that actually worked",
        "description": "Share your go-to cold email format or script \u2014 the one that got results. Break down why it worked and how others can tweak it for their own outreach.",
        "category": "how-to",
        "color": COLORS[2],
    },
    {
        "id": 6,
        "emoji": "\U0001f50d",
        "title": "Creators to follow in my niche",
        "description": "Highlight a curated list of people doing great work in your space. Tell us why they\u2019re worth following \u2014 and what you\u2019ve learned from them.",
        "category": "list",
        "color": COLORS[3],
    },
    {
        "id": 5,
        "emoji": "\U0001f6e0\ufe0f",
        "title": "My go-to tools for getting things done",
        "description": "Share the tools you rely on weekly \u2014 what they help you with, why you love them, and how they\u2019ve improved your work or creative flow.",
        "category": "list",
        "color": COLORS[4],
    },
    {
        "id": 4,
        "emoji": "\u26a1\ufe0f",
        "title": "How I stay productive without burning out",
        "description": "Talk about how you improved your focus without falling into hustle culture. What didn\u2019t work? What small change helped you get more done with less stress?",
        "category": "tip",
        "color": COLORS[5],
    },
    {
        "id": 3,
        "emoji": "\U0001f9e0",
        "title": "The fix was simpler than I expected",
        "description": "Describe a problem you overcomplicated \u2014 and the simple solution that actually solved it. Help others skip the trial and error.",
        "category": "tip",
        "color": COLORS[0],
    },
    {
        "id": 1,
        "emoji": "\U0001f4da",
        "title": "Books that changed how I work",
        "description": "Share a curated list of books that helped you level up in your career or craft \u2014 and why each one mattered.",
        "category": "list",
        "color": COLORS[1],
    },
]


def get_featured_templates():
    """Return the 3 featured templates."""
    by_id = {t["id"]: t for t in TEMPLATES}
    return [by_id[fid] for fid in FEATURED_IDS if fid in by_id]


def get_all_templates():
    """Return all templates."""
    return TEMPLATES
